"""add date_create in Event

Revision ID: 610c0310c549
Revises: d483bb54873e
Create Date: 2024-09-18 14:41:39.849824

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610c0310c549'
down_revision: Union[str, None] = 'd483bb54873e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_create', sa.DateTime(), nullable=False, server_default=str(datetime.utcnow())))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date_create')
    # ### end Alembic commands ###
